<a href="https://colab.research.google.com/github/parsaestakhry/colab-pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

  

```
# This is formatted as code
```

scalar.item()

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR1 = torch.tensor([[[[1, 2, 3] , [4, 5 , 6], [7, 8, 9], [2, 4 , 8]]]])
TENSOR1.ndim
TENSOR1.shape

TypeError: tensor() takes 1 positional argument but 2 were given

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors


In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5152, 0.9759, 0.3257, 0.4953],
        [0.2594, 0.3478, 0.8649, 0.9444],
        [0.4960, 0.8215, 0.7885, 0.7136]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# random tensor similar to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.shape

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]))

### Zeros and Ones

In [ ]:
# create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)

In [ ]:
ones.dtype

torch.float32

In [ ]:
ones_new = torch.ones(2,4,3,4)
ones_new

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

### Creating a Range of tensors and tensors-like

In [ ]:
# use torch.range
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, device="cuda", requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32, device="cuda")
int_32_tensor

tensor([3, 6, 9], device='cuda:0', dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Gettting informations from tensor

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2134, 0.1894, 0.3671, 0.8751],
        [0.3978, 0.8788, 0.6296, 0.7527],
        [0.4376, 0.6779, 0.1981, 0.1904]])

In [ ]:
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"tensor device: {some_tensor.device}")

tensor([[0.2134, 0.1894, 0.3671, 0.8751],
        [0.3978, 0.8788, 0.6296, 0.7527],
        [0.4376, 0.6779, 0.1981, 0.1904]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
tensor device: cpu


In [ ]:
new_tensor = torch.rand(2,3,4, device="cuda", dtype=torch.float64)
new_tensor

tensor([[[0.8874, 0.2229, 0.8798, 0.4081],
         [0.3734, 0.8614, 0.0804, 0.4771],
         [0.4076, 0.1418, 0.0484, 0.0780]],

        [[0.1557, 0.9891, 0.8601, 0.9133],
         [0.3053, 0.7195, 0.9410, 0.7009],
         [0.4363, 0.7291, 0.0580, 0.9790]]], device='cuda:0',
       dtype=torch.float64)

### Maniuplating the tensors

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
#Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 4)

tensor([5, 6, 7])

###Matrix Multiplication
two ways

In [ ]:
# Element wise multiplication
print(tensor,  "*",  tensor)
tensor * tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
1 * 1 + 2* 2 + 3 * 3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor [i]

value

CPU times: user 1.39 ms, sys: 25 µs, total: 1.42 ms
Wall time: 7.49 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.2 ms, sys: 11 µs, total: 1.21 ms
Wall time: 1.22 ms


tensor(14)

### One of the most common errors in deep learning

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[3.7205, 2.3088, 3.2469],
        [3.0248, 1.8990, 2.4273],
        [2.6534, 1.8079, 2.2380]])

#Shapes for matrix multiplication

In [ ]:
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10], [8,11], [9,12]])
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_C = torch.tensor([[1,2], [3,4], [5,6]])
tensor_D = torch.tensor([[7,10], [8,11]])
torch.mm(tensor_C, tensor_D)

tensor([[ 23,  32],
        [ 53,  74],
        [ 83, 116]])

## Finding min,max,sum .... (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
# Find the min
torch.min(x), x.min()
torch.max(x), x.max()
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# Find the sum
torch.sum(x), x.sum()


(tensor(450), tensor(450))

In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
x[torch.argmin(x)]

tensor(0)

In [ ]:
import torch
x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(4,3)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x,x], dim=1)
x_stacked


tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [ ]:
# torch.squeeze()
x_reshaped

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
x_reshaped.shape

torch.Size([4, 3])

In [ ]:
x_reshaped.squeeze()

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [3]:
hello = torch.arange(1, 10, step=1)
hello

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
hello.shape

torch.Size([9])

In [ ]:
hello.squeeze(

)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
torch.unsqueeze(hello, dim=1)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
x = torch.rand(2,3,4)
torch.permute(x, (2, 0,1))


tensor([[[0.6419, 0.8368, 0.2021],
         [0.8279, 0.5371, 0.6424]],

        [[0.8010, 0.2864, 0.2333],
         [0.2176, 0.9692, 0.6361]],

        [[0.2827, 0.4542, 0.4478],
         [0.5312, 0.8558, 0.1820]],

        [[0.1488, 0.8538, 0.9528],
         [0.5363, 0.7772, 0.0961]]])

In [18]:
x_original = torch.rand(size=(224,224,3))
x_original

# Premute to rearrange the axis or dimensions
x_original = torch.permute(x_original, (2, 0, 1))
x_original

tensor([[[0.1395, 0.6539, 0.7404,  ..., 0.1700, 0.1190, 0.3380],
         [0.2348, 0.7092, 0.1807,  ..., 0.0044, 0.4181, 0.9813],
         [0.7969, 0.3322, 0.9012,  ..., 0.0922, 0.2254, 0.7117],
         ...,
         [0.5845, 0.3659, 0.9673,  ..., 0.2884, 0.9266, 0.7335],
         [0.2055, 0.0706, 0.7323,  ..., 0.1616, 0.9914, 0.8693],
         [0.6729, 0.9045, 0.8623,  ..., 0.5303, 0.1395, 0.9154]],

        [[0.1934, 0.7262, 0.2020,  ..., 0.7055, 0.2566, 0.2499],
         [0.9480, 0.9123, 0.2185,  ..., 0.0330, 0.9487, 0.2561],
         [0.1853, 0.6298, 0.5266,  ..., 0.5251, 0.6179, 0.4009],
         ...,
         [0.1880, 0.1223, 0.2465,  ..., 0.3329, 0.1704, 0.6993],
         [0.5229, 0.3542, 0.9462,  ..., 0.3399, 0.4662, 0.4176],
         [0.4219, 0.7886, 0.3716,  ..., 0.7429, 0.4975, 0.7793]],

        [[0.7513, 0.8159, 0.5183,  ..., 0.3852, 0.0479, 0.6872],
         [0.4867, 0.5574, 0.5049,  ..., 0.2359, 0.3936, 0.4978],
         [0.6275, 0.8041, 0.4581,  ..., 0.3548, 0.5349, 0.

## Indexing

In [25]:
# Creating a tensor
import torch
x = torch.arange(1,10,step=1).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [26]:
# index on tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
x[0][0]

tensor([1, 2, 3])

In [28]:
x[0][0][0]

tensor(1)

In [29]:
# getting the number 9
x[0][2][2]

tensor(9)

In [31]:
x[:,:,1]

tensor([[2, 5, 8]])

In [32]:
x[:,1,1]

tensor([5])

In [33]:
x[0,0,:]

tensor([1, 2, 3])

In [34]:
x[0,2,2]

tensor(9)

In [35]:
x[0,0,2], x[0,1,2]

(tensor(3), tensor(6))

In [36]:
# numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [39]:
# reproducibility trying to take random out of random
torch.rand(3,3)

tensor([[0.8882, 0.7208, 0.7742],
        [0.6453, 0.5356, 0.1225],
        [0.8158, 0.5587, 0.0910]])

In [42]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A,random_tensor_B
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])